language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - python setup.py install
  - pip install nose flake8 hacking

script:
  - nosetests -a '!gpu' tests/chainer_tests
  - flake8 chainer cupy tests examples --exclude=libcudnn.py,caffe_pb2.py

sudo: false
