language: python

cache:
  - pip
  - ccache

matrix:
  include:
    - dist: trusty
      python: "2.7"
      env:
      - CHAINER_TRAVIS_TEST="chainer"
      - SKIP_CHAINERX=1

    - dist: trusty
      python: "3.4"
      env:
      - CHAINER_TRAVIS_TEST="chainer"
      - SKIP_CHAINERX=1

    - dist: xenial
      python: "3.5"
      env:
      - CHAINER_TRAVIS_TEST="chainer"
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: osx
      language: generic
      env:
      - CHAINER_TRAVIS_TEST="chainer"
      - PYTHON_VERSION=2.7.10
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
      - SKIP_CHAINERX=1
      if: (branch = master OR branch = v5) AND (NOT type in (pull_request))

    - os: osx
      language: generic
      env:
      - CHAINER_TRAVIS_TEST="chainer"
      - PYTHON_VERSION=3.4.4
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
      - SKIP_CHAINERX=1
      if: (branch = master OR branch = v5) AND (NOT type in (pull_request))

    - os: osx
      language: generic
      env:
      - CHAINER_TRAVIS_TEST="chainer"
      - PYTHON_VERSION=3.5.1
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
      - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"
      if: (branch = master OR branch = v5) AND (NOT type in (pull_request))

before_install:
  - bash scripts/ci/travis/run-tests.sh before_install

install:
  - travis_wait bash scripts/ci/travis/run-tests.sh install

script:
  - bash scripts/ci/travis/run-tests.sh script

sudo: false

addons:
  apt:
    packages:
      - gfortran
      - libhdf5-serial-dev
      - liblapack-dev
      - openmpi-bin
      - openmpi-common
      - libopenmpi-dev
