version: 2
jobs:
  clang-format:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y clang-format

      - run: |
          clang-format --version

      - run: |
          find xchainer \( -name '*.cc' -o -name '*.h' \) -type f -print0 | xargs -0 -P4 -I{} bash -c 'diff -u {} <(clang-format {})'

  build:
    docker:
      - image: ubuntu:xenial
    steps:

      - restore_cache:
          keys:
            - downloads-cache

      # Checkout
      - checkout

      # Setup
      - run:
          name: Setup
          command: |
            mkdir -p downloads
            apt-get update
            apt-get install -y g++ cmake clang clang-format clang-tidy git python3-dev lcov wget
            apt-get install -y bzip2  # To install miniconda

            # conda
            if [ ! -f downloads/miniconda.sh ]; then
              wget 'https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh' -O downloads/miniconda.sh
            fi
            bash downloads/miniconda.sh -b -p "$HOME"/miniconda
            export PATH="$HOME"/miniconda/bin:"$PATH"
            conda config --set changeps1 no
            conda update -y -q conda
            conda create -y -q --name testenv python=3.6 pip

      - save_cache:
          key: downloads-cache
          paths:
            - downloads

      # Environment info
      - run:
          name: Environment info
          command: |
            export PATH="$HOME"/miniconda/bin:"$PATH"
            source activate testenv

            echo "PWD: $PWD"

            g++ --version
            cmake --version
            python --version

            echo
            echo "----- conda -----"
            conda info -a

      # C++ test 
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "CMakeLists.txt" }}

      - run:
          name: C++ test
          command: |
            export PATH="$HOME"/miniconda/bin:"$PATH"
            source activate testenv

            ( mkdir -p build && cd build && cmake -DBUILD_PYTHON=1 -DENABLE_COVERAGE=ON .. && make clang-tidy && make && ctest -V )
            lcov -c -b xchainer -d build/xchainer/ --no-external -o build/coverage.info
            genhtml build/coverage.info -o build/coverage

      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "CMakeLists.txt" }}
          paths:
            - build

      - store_artifacts:
          path: build/coverage

      # Setup conda environment
      - run:
          name: Setup conda environment
          command: |
            export PATH="$HOME"/miniconda/bin:"$PATH"
            source activate testenv

            pip install -U hacking autopep8
            pip install -U pytest pytest-cov coveralls

      # Python PEP-8 check
      - restore_cache:
          key: dependency-cache-pip-{{ .Branch }}-{{ .Revision }}

      - save_cache:
          key: dependency-cache-pip-{{ .Branch }}-{{ .Revision }}
          paths:
            - "venv"

      - run:
          name: Python PEP-8 check
          command: |
            export PATH="$HOME"/miniconda/bin:"$PATH"
            source activate testenv

            flake8 --version
            flake8 xchainer tests

            autopep8 --version
            autopep8 xchainer tests -r --global-config .pep8 --diff | tee check_autopep8
            test ! -s check_autopep8

      # Python test
      - run:
          name: Python test
          command: |
            export PATH="$HOME"/miniconda/bin:"$PATH"
            source activate testenv

            python setup.py install
            # TODO(niboshi): coverage does not work
            #pytest --cov --no-cov-on-fail --cov-fail-under=80
            pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - clang-format
      - build
