version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y g++ cmake

      - run: |
          g++ --version
          cmake --version

      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "CMakeLists.txt" }}

      - run: mkdir -p build && cd build && cmake .. && make

      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "CMakeLists.txt" }}
          paths:
            - build
  python-lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-pip-{{ .Branch }}-{{ .Revision }}

      - run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install hacking
          pip install autopep8

      - save_cache:
          key: dependency-cache-pip-{{ .Branch }}-{{ .Revision }}
          paths:
            - "venv"

      - run: |
          . venv/bin/activate
          flake8 --version
          flake8 xchainer

      - run: |
          . venv/bin/activate
          autopep8 --version
          autopep8 -r xchainer --global-config .pep8 --diff | tee check_autopep8
          test ! -s check_autopep8

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - python-lint
