version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y g++ cmake clang clang-tidy git python3-dev lcov

      - run: |
          g++ --version
          cmake --version

      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "CMakeLists.txt" }}

      - run: |
          ( mkdir -p build && cd build && cmake -DBUILD_PYTHON=1 -DENABLE_COVERAGE=ON .. && make clang-tidy && make && ctest -V )
          lcov -c -b xchainer -d build/xchainer/ --no-external -o build/coverage.info
          genhtml build/coverage.info -o build/coverage

      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "CMakeLists.txt" }}
          paths:
            - build

      - store_artifacts:
          path: build/coverage

  clang-format:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y clang-format

      - run: |
          clang-format --version

      - run: |
          find xchainer \( -name '*.cc' -o -name '*.h' \) -type f -print0 | xargs -0 -P4 -I{} bash -c 'diff -u {} <(clang-format {})'

  python-lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-pip-{{ .Branch }}-{{ .Revision }}

      - run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install hacking
          pip install autopep8

      - save_cache:
          key: dependency-cache-pip-{{ .Branch }}-{{ .Revision }}
          paths:
            - "venv"

      - run: |
          . venv/bin/activate
          flake8 --version
          flake8 xchainer

      - run: |
          . venv/bin/activate
          autopep8 --version
          autopep8 -r xchainer --global-config .pep8 --diff | tee check_autopep8
          test ! -s check_autopep8

workflows:
  version: 2
  build_and_test:
    jobs:
      - clang-format
      - python-lint
      - build
