version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y g++ cmake

      - run: |
          g++ --version
          cmake --version

      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "CMakeLists.txt" }}

      - run: mkdir -p build && cd build && cmake .. && make

      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "CMakeLists.txt" }}
          paths:
            - build
  python-3.5:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install autopep8
          pip install flake8

      - run: |
          . venv/bin/activate
          flake8 --version
          flake8 . | tee check_flake8

      - store_artifacts:
          path: check_flake8

      - run: |
          . venv/bin/activate
          autopep8 --version
          autopep8 -r . --global-config .pep8 --diff | tee check_autopep8

      - store_artifacts:
          path: check_autopep8

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - python-3.5
